FROM node:16 as build-stage

# Set the working directory
WORKDIR /frontend

# Copy package.json and package-lock.json for dependency installation
COPY ./frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the entire frontend source code
COPY ./frontend ./

# Build the Vue.js application
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /frontend/dist /app
COPY nginx.conf /etc/nginx/nginx.conf